### ISSUE TITLE
Typo in Driver/GnuPG/Cli.php

### ISSUE THREAD

**Issue by otherguy** [travisghansen/phpgpg#1]
Hi!

First of all, great package! :) 

I found a small typo in `Cli.php` in line 1021.

``` php
case PhpGpg::SIG_MODE_DETACHED:
```

should be 

``` php
case PhpGpg::SIG_MODE_DETACH:
```

Would be awesome if you could fix it.

**Comment by otherguy** [comment]
And another one in the same file. This needs to be removed:

``` php
// ignore for now
if ($textmode) {
    $arguments[] = '--textmode';
}
```

**Comment by travisghansen** [comment]
Thanks for the heads up!  All the hard work (for the cli driver) was done by the pear project.  I gutted a bunch of it but still have several things that never got cleaned up apparently.  Just pushed v0.0.6 in case you're using composer.

**Comment by otherguy** [comment]
I do, thanks :) :+1:
