### ISSUE TITLE
Bug when throwing an exception in Driver/GnuPG/Cli/Engine::_openSubprocess()

### ISSUE THREAD

**Issue by JakubMatejka** [travisghansen/phpgpg#3]
Hi,
Here is a bug: https://github.com/travisghansen/phpgpg/blob/master/src/PhpGpg/Driver/GnuPG/Cli/Engine.php#L1391
Third argument of `\Exception` should be previous exception, not `$commandLine` string.

**Comment by travisghansen** [comment]
Thanks for the report.  I've fixed and published v0.0.7 with the fix.
